workflows:
  android-workflow:
    name: Snake Rivals Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - credentials # سنقوم بإنشاء هذه المجموعة في الموقع
    scripts:
      - name: Create .env file
        script: |
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
